import type { Metadata } from "next";
import { Faculty_Glyphic, Nunito_Sans } from "next/font/google";
import "./globals.css";

const nunitoSans = Nunito_Sans({variable:'--font-sans'});

const flared = Faculty_Glyphic({
  variable: "--font-faculty-glyphic",
  weight: "400",
});

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

export const metadata: Metadata = {
  title: "Knitspace",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={nunitoSans.variable}>
      <body className={`${flared.variable} antialiased`}>{children}</body>
    </html>
  );
}
